name: Docker build
on:
  push:
    branches:
      - main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout
    
    - name: Login to docker hub
      uses: docker/login-actions
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Setup docker buildx
      id: buildx
      uses: docker/setup-buildx-actions

    - name: Build and push
      id: docker_build
      uses: docker/build-push-actions
      with:
        context: ./
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME}}/steamcmd:${{steps.vars.outputs.tag}}